### ISSUE TITLE
下拉

### ISSUE THREAD

**Issue by ZachGuoMingyu** [ice-vigorous/YiceSlideslipPickMenu#1]
您好，这个要改成下拉的可行吗

**Comment by ice-vigorous** [comment]
可以的。你指的下拉是父选项栏在屏幕顶部是吗？然后点击父选项展示子选项是不是？

**Comment by ice-vigorous** [comment]
> 您好，这个要改成下拉的可行吗
可以的。你指的下拉是父选项栏在屏幕顶部是吗？然后点击父选项展示子选项是不是？

**Comment by ice-vigorous** [comment]
> 您好，这个要改成下拉的可行吗

可以的。你指的下拉是父选项栏在屏幕顶部是吗？然后点击父选项展示子选项是不是？

**Comment by ZachGuoMingyu** [comment]
> > 您好，这个要改成下拉的可行吗
> 
> 可以的。你指的下拉是父选项栏在屏幕顶部是吗？然后点击父选项展示子选项是不是？

对的 只不过子选项是以collectionview显示的

**Comment by ice-vigorous** [comment]
> > > 您好，这个要改成下拉的可行吗
> > 
> > 
> > 可以的。你指的下拉是父选项栏在屏幕顶部是吗？然后点击父选项展示子选项是不是？
> 
> 对的 只不过子选项是以collectionview显示的

**Comment by ice-vigorous** [comment]
> > > 您好，这个要改成下拉的可行吗
> > 
> > 
> > 可以的。你指的下拉是父选项栏在屏幕顶部是吗？然后点击父选项展示子选项是不是？
> 
> 对的 只不过子选项是以collectionview显示的

那相对要简单一点呀，你可以参照我另外一个Menu，那个奇葩的menu在父选项之下还有多个二级父选项，然后才有的子选项，并且子选项的宽度不是固定的。你看下思路自己综合一下就可以了。
这个demo我后面看有时间的话可以把它优化下，代理换block这样接口就不用都抛给viewController，同时兼容右滑和左滑以及下拉，看能不能优化成第三方库。最近工作有些事，没什么时间整理、很抱歉
